// flow-typed signature: e382592e52f6e9930da5286ae8e29e49
// flow-typed version: <<STUB>>/dox_v^0.9.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dox/lib/api' {
  declare module.exports: any;
}

declare module 'dox/lib/dox' {
  declare module.exports: any;
}

declare module 'dox/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dox/index' {
  declare module.exports: $Exports<'dox'>;
}
declare module 'dox/index.js' {
  declare module.exports: $Exports<'dox'>;
}
declare module 'dox/lib/api.js' {
  declare module.exports: $Exports<'dox/lib/api'>;
}
declare module 'dox/lib/dox.js' {
  declare module.exports: $Exports<'dox/lib/dox'>;
}
declare module 'dox/lib/utils.js' {
  declare module.exports: $Exports<'dox/lib/utils'>;
}
