// flow-typed signature: aefdee7d605ecf3e4a8401e24d86ba6c
// flow-typed version: <<STUB>>/elasticsearch_v^12.1.3/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'elasticsearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'elasticsearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'elasticsearch/src/elasticsearch.angular' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/elasticsearch.jquery' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/elasticsearch' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/0_90' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/1_0' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/1_1' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/1_2' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/1_3' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/1_4' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/1_5' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/1_6' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/1_7' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/2_0' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/2_1' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/2_2' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/2_3' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/2_4' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/5_0' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/5_x' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/browser_index' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/index' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/apis/master' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/client_action' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/client' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connection_pool' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connection' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connectors/_keep_alive_agent' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connectors/angular' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connectors/browser_index' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connectors/http' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connectors/index' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connectors/jquery' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/connectors/xhr' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/errors' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/host' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/log' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/logger' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/loggers/browser_index' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/loggers/console' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/loggers/file' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/loggers/index' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/loggers/stdio' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/loggers/stream' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/loggers/tracer' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/nodes_to_host' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/selectors/index' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/selectors/random' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/selectors/round_robin' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/serializers/angular' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/serializers/index' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/serializers/json' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/transport' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/transport/find_common_protocol' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/transport/sniff_on_connection_fault' {
  declare module.exports: any;
}

declare module 'elasticsearch/src/lib/utils' {
  declare module.exports: any;
}

declare module 'elasticsearch/webpack_config/angular' {
  declare module.exports: any;
}

declare module 'elasticsearch/webpack_config/browser' {
  declare module.exports: any;
}

declare module 'elasticsearch/webpack_config/jquery' {
  declare module.exports: any;
}

declare module 'elasticsearch/webpack_config/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'elasticsearch/src/elasticsearch.angular.js' {
  declare module.exports: $Exports<'elasticsearch/src/elasticsearch.angular'>;
}
declare module 'elasticsearch/src/elasticsearch.jquery.js' {
  declare module.exports: $Exports<'elasticsearch/src/elasticsearch.jquery'>;
}
declare module 'elasticsearch/src/elasticsearch.js' {
  declare module.exports: $Exports<'elasticsearch/src/elasticsearch'>;
}
declare module 'elasticsearch/src/lib/apis/0_90.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/0_90'>;
}
declare module 'elasticsearch/src/lib/apis/1_0.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/1_0'>;
}
declare module 'elasticsearch/src/lib/apis/1_1.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/1_1'>;
}
declare module 'elasticsearch/src/lib/apis/1_2.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/1_2'>;
}
declare module 'elasticsearch/src/lib/apis/1_3.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/1_3'>;
}
declare module 'elasticsearch/src/lib/apis/1_4.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/1_4'>;
}
declare module 'elasticsearch/src/lib/apis/1_5.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/1_5'>;
}
declare module 'elasticsearch/src/lib/apis/1_6.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/1_6'>;
}
declare module 'elasticsearch/src/lib/apis/1_7.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/1_7'>;
}
declare module 'elasticsearch/src/lib/apis/2_0.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/2_0'>;
}
declare module 'elasticsearch/src/lib/apis/2_1.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/2_1'>;
}
declare module 'elasticsearch/src/lib/apis/2_2.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/2_2'>;
}
declare module 'elasticsearch/src/lib/apis/2_3.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/2_3'>;
}
declare module 'elasticsearch/src/lib/apis/2_4.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/2_4'>;
}
declare module 'elasticsearch/src/lib/apis/5_0.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/5_0'>;
}
declare module 'elasticsearch/src/lib/apis/5_x.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/5_x'>;
}
declare module 'elasticsearch/src/lib/apis/browser_index.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/browser_index'>;
}
declare module 'elasticsearch/src/lib/apis/index.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/index'>;
}
declare module 'elasticsearch/src/lib/apis/master.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/apis/master'>;
}
declare module 'elasticsearch/src/lib/client_action.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/client_action'>;
}
declare module 'elasticsearch/src/lib/client.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/client'>;
}
declare module 'elasticsearch/src/lib/connection_pool.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connection_pool'>;
}
declare module 'elasticsearch/src/lib/connection.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connection'>;
}
declare module 'elasticsearch/src/lib/connectors/_keep_alive_agent.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connectors/_keep_alive_agent'>;
}
declare module 'elasticsearch/src/lib/connectors/angular.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connectors/angular'>;
}
declare module 'elasticsearch/src/lib/connectors/browser_index.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connectors/browser_index'>;
}
declare module 'elasticsearch/src/lib/connectors/http.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connectors/http'>;
}
declare module 'elasticsearch/src/lib/connectors/index.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connectors/index'>;
}
declare module 'elasticsearch/src/lib/connectors/jquery.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connectors/jquery'>;
}
declare module 'elasticsearch/src/lib/connectors/xhr.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/connectors/xhr'>;
}
declare module 'elasticsearch/src/lib/errors.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/errors'>;
}
declare module 'elasticsearch/src/lib/host.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/host'>;
}
declare module 'elasticsearch/src/lib/log.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/log'>;
}
declare module 'elasticsearch/src/lib/logger.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/logger'>;
}
declare module 'elasticsearch/src/lib/loggers/browser_index.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/loggers/browser_index'>;
}
declare module 'elasticsearch/src/lib/loggers/console.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/loggers/console'>;
}
declare module 'elasticsearch/src/lib/loggers/file.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/loggers/file'>;
}
declare module 'elasticsearch/src/lib/loggers/index.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/loggers/index'>;
}
declare module 'elasticsearch/src/lib/loggers/stdio.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/loggers/stdio'>;
}
declare module 'elasticsearch/src/lib/loggers/stream.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/loggers/stream'>;
}
declare module 'elasticsearch/src/lib/loggers/tracer.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/loggers/tracer'>;
}
declare module 'elasticsearch/src/lib/nodes_to_host.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/nodes_to_host'>;
}
declare module 'elasticsearch/src/lib/selectors/index.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/selectors/index'>;
}
declare module 'elasticsearch/src/lib/selectors/random.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/selectors/random'>;
}
declare module 'elasticsearch/src/lib/selectors/round_robin.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/selectors/round_robin'>;
}
declare module 'elasticsearch/src/lib/serializers/angular.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/serializers/angular'>;
}
declare module 'elasticsearch/src/lib/serializers/index.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/serializers/index'>;
}
declare module 'elasticsearch/src/lib/serializers/json.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/serializers/json'>;
}
declare module 'elasticsearch/src/lib/transport.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/transport'>;
}
declare module 'elasticsearch/src/lib/transport/find_common_protocol.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/transport/find_common_protocol'>;
}
declare module 'elasticsearch/src/lib/transport/sniff_on_connection_fault.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/transport/sniff_on_connection_fault'>;
}
declare module 'elasticsearch/src/lib/utils.js' {
  declare module.exports: $Exports<'elasticsearch/src/lib/utils'>;
}
declare module 'elasticsearch/webpack_config/angular.js' {
  declare module.exports: $Exports<'elasticsearch/webpack_config/angular'>;
}
declare module 'elasticsearch/webpack_config/browser.js' {
  declare module.exports: $Exports<'elasticsearch/webpack_config/browser'>;
}
declare module 'elasticsearch/webpack_config/jquery.js' {
  declare module.exports: $Exports<'elasticsearch/webpack_config/jquery'>;
}
declare module 'elasticsearch/webpack_config/lib.js' {
  declare module.exports: $Exports<'elasticsearch/webpack_config/lib'>;
}
