// flow-typed signature: 6c5ededc1a2bdda61573b532d894bfbc
// flow-typed version: <<STUB>>/jest-babel_v^1.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-babel/index' {
  declare module.exports: $Exports<'jest-babel'>;
}
declare module 'jest-babel/index.js' {
  declare module.exports: $Exports<'jest-babel'>;
}
