"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.getPercentilesITC = getPercentilesITC;

var _graphqlCompose = require("graphql-compose");

var _utils = require("../../../utils");

var _Script = require("../../Commons/Script");

var _HDR = require("../../Commons/HDR");

var _FieldNames = require("../../Commons/FieldNames");

function getPercentilesITC(opts = {}) {
  const name = (0, _utils.getTypeName)('AggsPercentiles', opts);
  const description = (0, _utils.desc)(`
    A multi-value metrics aggregation that calculates one or more percentiles
    over numeric values extracted from the aggregated documents.
    These values can be extracted either from specific numeric fields
    in the documents, or be generated by a provided script.
    [Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html)
  `);
  return (0, _utils.getOrSetType)(name, () => _graphqlCompose.InputTypeComposer.create({
    name,
    description,
    fields: {
      field: (0, _FieldNames.getNumericFields)(opts),
      percents: '[Float]',
      tdigest: `input ${(0, _utils.getTypeName)('AggsPercentilesTDigest', opts)} {
          compression: Int,
        }`,
      hdr: () => (0, _HDR.getCommonsHdrITC)(opts),
      missing: 'Float',
      script: () => (0, _Script.getCommonsScriptITC)(opts)
    }
  }));
}