import { InputTypeComposer } from 'graphql-compose';
import { getTypeName, CommonOpts, desc } from '../../../utils';
import { getCommonsScriptITC } from '../../Commons/Script';
import { getAllFields } from '../../Commons/FieldNames';

export function getCardinalityITC<TContext>(
  opts: CommonOpts<TContext>
): InputTypeComposer<TContext> {
  const name = getTypeName('AggsCardinality', opts);
  const description = desc(
    `
    A single-value metrics aggregation that calculates an approximate count
    of distinct values. Values can be extracted either from specific fields
    in the document or generated by a script.
    [Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html)
  `
  );

  return opts.getOrCreateITC(name, () => ({
    name,
    description,
    fields: {
      field: getAllFields(opts),
      precision_threshold: {
        type: 'Int',
        defaultValue: 3000,
        description: desc(
          `
            Allows to trade memory for accuracy, and defines a unique count
            below which counts are expected to be close to accurate.
          `
        ),
      },
      missing: 'String',
      script: (): InputTypeComposer<TContext> => getCommonsScriptITC(opts),
    },
  }));
}
